#!/bin/bash

for i in {1..9}

do

      ping rpi0$i -w 3 > /dev/null

      if [$? -eq 0]; then
        echo "rpi0$i is active"
                else
        echo "rpi0$i is inactive"
      fi

for i in {10..20}

do

      ping rpi$i -w 3 > /dev/null

      if [$? -eq 0]; then
        echo "rpi$i is active"
                else
        echo "rpi$i is inactive"
      fi
done

exit 0
