#!/bin/bash

#set up list of raspberry pi
RPILIST="rpi1, rpi2, rpi3, rpi4, rpi5, rpi6, rpi7, rpi8, rpi9, rpi10, rpi11, rpi12, rpi13, rpi14, rpi15, rpi16, rpi17, rpi18, rpi19, rpi20"
RPIIPLIST="172.19.223.92, 172.19.223.91, 172.19.223.100" 
NUM=1

#starts the echo
echo

#starts the for loop
for device in $RPILIST ; do
	fping -c1 -t300 $device 2>/dev/null 1>/dev/null
	if [ "$?" > 2 ]
	then
  		echo "rpi$NUM found"
	else
  		echo "rpi$NUM not found"
	fi
	echo
	NUM=$[NUM+1]
done

#ends code
exit 0
