#!/bin/bash

#sets up the rpi header to cocat onto the variable
header="rpi"

#checks if in range of 01 to 20 (and then pings said device)and returns list of all availible if th$
if [ $# -eq 0 ]
then
        for i in $(seq -w 01 20)
        do
        CONCAT=$header$i
        SYSTEM=`ping -c 1 $CONCAT`
        STATUS=`echo $?`

        if [ $STATUS -eq  0 ]
        then
                echo "$CONCAT: is online"
        else
                echo "$CONCAT: is not online"
        fi
        done

# if not in range, specified number, will check
else
        for i
        do
        SYSTEM=`ping -c 1 $i`
        STATUS=`echo $?`

        if [ $STATUS -eq 0 ]
        then
                echo "$i: is online"
        else
                echo "$i: is not online"
        fi
        done
fi
exit 0
